_ = require('lodash')
moment = require('moment')
Groups = new Mongo.Collection('groups')
Activities = new Mongo.Collection('activities')
Users = new Mongo.Collection('users')
Issues = new Mongo.Collection('issues')
